@extends('layouts.app')
@section('title','Editor Kuesioner')
@section('heading',$survey->exists?'Edit kuesioner':'Buat kuesioner')
@section('subtitle','Atur pertanyaan, periode, dan status publikasi survei.')
@section('actions')@if($survey->exists)<a class="btn" href="{{ route('surveys.preview',$survey) }}" target="_blank" rel="noopener">Pratinjau tersimpan ↗</a>@endif @endsection
@section('content')<form method="post" action="{{ $survey->exists?route('surveys.update',$survey):route('surveys.store') }}" class="editor-form">@csrf @if($survey->exists)@method('put')<input type="hidden" name="version" value="{{ $survey->version }}">@endif
<section class="panel form-panel"><h2>Informasi kuesioner</h2><div class="form-grid"><label class="full">Judul<input name="title" value="{{ old('title',$survey->title) }}" maxlength="255" required></label><label class="full">Pengantar<textarea name="description" rows="3">{{ old('description',$survey->description) }}</textarea></label><label>Tanggal mulai<input type="date" name="starts_at" required value="{{ old('starts_at',$survey->starts_at?->format('Y-m-d')) }}"></label><label>Tanggal selesai<input type="date" name="ends_at" required value="{{ old('ends_at',$survey->ends_at?->format('Y-m-d')) }}"></label><label>Status<select name="status">@foreach(['draft'=>'Draf','active'=>'Aktif','closed'=>'Ditutup'] as $key=>$text)<option value="{{ $key }}" @selected(old('status',$survey->status)===$key)>{{ $text }}</option>@endforeach</select></label><label class="check-row"><input type="hidden" name="is_template" value="0"><input type="checkbox" name="is_template" value="1" @checked(old('is_template',$survey->is_template))> Simpan sebagai template</label></div></section>
<div class="section-heading"><h2>Daftar pertanyaan</h2><span class="badge green">Komentar wajib untuk skor 1–3</span></div>
@if($locked)<div class="notice">Pertanyaan dikunci karena kuesioner sudah memiliki undangan. Gunakan Duplikat untuk membuat versi baru.</div>@foreach($survey->questions as $q)<section class="panel form-panel"><span class="eyebrow">{{ $q->category }} / {{ $q->type }}</span><h3>{{ $loop->iteration }}. {{ $q->text }}</h3><p class="muted">{{ $q->required?'Wajib':'Opsional' }}</p></section>@endforeach
@else
@php($initial=old('questions',$survey->questions->map(fn($q)=>['text'=>$q->text,'category'=>$q->category,'type'=>$q->type,'required'=>$q->required,'options'=>implode("\n",$q->options??[])])->values()->all()))
<script type="application/json" id="initial-questions">@json($initial)</script><script type="application/json" id="question-bank">@json($bank)</script>
<div id="question-editor"></div><template id="question-template"><section class="question-editor"><div class="question-editor-header"><strong data-question-number></strong><div><button type="button" class="icon-link" data-move="-1" aria-label="Pindah ke atas">↑</button><button type="button" class="icon-link" data-move="1" aria-label="Pindah ke bawah">↓</button><button type="button" class="text-button danger" data-remove>Hapus</button></div></div><label>Pertanyaan<textarea data-field="text" rows="2" maxlength="2000" required></textarea></label><div class="form-grid"><label>Kategori<input data-field="category" required maxlength="100"></label><label>Jenis<select data-field="type"><option value="rating">Rating 1–5</option><option value="choice">Pilihan ganda</option><option value="text">Teks terbuka</option></select></label></div><label data-options-label>Pilihan jawaban (satu per baris)<textarea data-field="options" rows="3"></textarea></label><label class="check-row"><input type="hidden" data-required-default value="0"><input type="checkbox" data-field="required" value="1"> Wajib diisi</label></section></template>
<div class="editor-buttons"><button type="button" class="btn" id="add-question">＋ Tambah pertanyaan</button><select id="bank-select" aria-label="Tambah dari bank"><option value="">Ambil dari bank pertanyaan</option>@foreach($bank as $b)<option value="{{ $b->id }}">{{ $b->text }}</option>@endforeach</select></div><noscript><div class="notice error">Aktifkan JavaScript untuk menggunakan editor pertanyaan.</div></noscript>
@endif<div class="form-actions"><a class="btn" href="{{ route('surveys.index') }}">Kembali</a><button class="btn primary">Simpan kuesioner</button></div><p class="footnote">Untuk pratinjau sebelum publikasi, simpan dengan status Draf, lalu klik Pratinjau tersimpan. Aktifkan setelah isi dan periode sudah benar.</p></form>@endsection
