<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('users',function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->unique();$t->string('password');$t->string('role',20)->default('viewer');$t->rememberToken();$t->timestamps();});
  Schema::create('sessions',function(Blueprint $t){$t->string('id')->primary();$t->foreignId('user_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->longText('payload');$t->integer('last_activity')->index();});
  Schema::create('cache',function(Blueprint $t){$t->string('key')->primary();$t->mediumText('value');$t->integer('expiration');});
  Schema::create('cache_locks',function(Blueprint $t){$t->string('key')->primary();$t->string('owner');$t->integer('expiration');});
  Schema::create('jobs',function(Blueprint $t){$t->id();$t->string('queue')->index();$t->longText('payload');$t->unsignedTinyInteger('attempts');$t->unsignedInteger('reserved_at')->nullable();$t->unsignedInteger('available_at');$t->unsignedInteger('created_at');});
  Schema::create('failed_jobs',function(Blueprint $t){$t->id();$t->string('uuid')->unique();$t->text('connection');$t->text('queue');$t->longText('payload');$t->longText('exception');$t->timestamp('failed_at')->useCurrent();});
  Schema::create('clients',function(Blueprint $t){$t->id();$t->string('name');$t->string('contact');$t->string('email');$t->string('project')->index();$t->boolean('active')->default(true);$t->boolean('is_demo')->default(false);$t->timestamps();});
  Schema::create('surveys',function(Blueprint $t){$t->id();$t->string('title');$t->text('description')->nullable();$t->string('status',20)->default('draft')->index();$t->date('starts_at');$t->date('ends_at');$t->boolean('is_template')->default(false);$t->boolean('is_demo')->default(false);$t->unsignedInteger('version')->default(1);$t->foreignId('created_by')->constrained('users');$t->timestamps();});
  Schema::create('questions',function(Blueprint $t){$t->id();$t->foreignId('survey_id')->constrained()->cascadeOnDelete();$t->text('text');$t->string('category',100);$t->string('type',20);$t->boolean('required')->default(true);$t->json('options')->nullable();$t->unsignedInteger('position');$t->timestamps();$t->index(['survey_id','position']);});
  Schema::create('bank_questions',function(Blueprint $t){$t->id();$t->text('text');$t->string('category',100);$t->string('type',20);$t->boolean('required')->default(true);$t->json('options')->nullable();$t->timestamps();});
  Schema::create('invitations',function(Blueprint $t){$t->id();$t->foreignId('survey_id')->constrained();$t->foreignId('client_id')->constrained();$t->string('token_hash',64)->unique();$t->text('token');$t->string('recipient_email');$t->string('recipient_name');$t->json('draft_answers')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamp('sent_at')->nullable();$t->dateTime('reminder_at')->nullable()->index();$t->unsignedInteger('reminder_count')->default(0);$t->boolean('is_demo')->default(false);$t->timestamps();$t->unique(['survey_id','client_id']);});
  Schema::create('survey_responses',function(Blueprint $t){$t->id();$t->foreignId('invitation_id')->unique()->constrained();$t->foreignId('survey_id')->constrained();$t->foreignId('client_id')->constrained();$t->decimal('score',5,2)->nullable();$t->timestamp('submitted_at')->index();$t->timestamps();});
  Schema::create('answers',function(Blueprint $t){$t->id();$t->foreignId('survey_response_id')->constrained()->cascadeOnDelete();$t->foreignId('question_id')->constrained();$t->text('question_text');$t->string('category',100);$t->string('type',20);$t->text('value')->nullable();$t->text('comment')->nullable();$t->timestamps();$t->unique(['survey_response_id','question_id']);});
  Schema::create('follow_ups',function(Blueprint $t){$t->id();$t->foreignId('survey_response_id')->unique()->constrained();$t->foreignId('assigned_to')->nullable()->constrained('users');$t->string('status',20)->default('open')->index();$t->date('due_at')->nullable();$t->text('notes')->nullable();$t->timestamp('resolved_at')->nullable();$t->unsignedInteger('version')->default(1);$t->timestamps();});
  Schema::create('email_deliveries',function(Blueprint $t){$t->id();$t->foreignId('invitation_id')->constrained();$t->string('kind',20);$t->string('dedupe_key')->unique();$t->string('status',20)->default('pending')->index();$t->timestamp('sent_at')->nullable();$t->timestamp('queued_at')->nullable();$t->text('last_error')->nullable();$t->timestamps();});
 }
 public function down(): void {foreach(['email_deliveries','follow_ups','answers','survey_responses','invitations','bank_questions','questions','surveys','clients','failed_jobs','jobs','cache_locks','cache','sessions','users'] as $table){Schema::dropIfExists($table);}}
};
