@extends('layouts.app')
@section('title','Distribusi')
@section('heading','Distribusi & reminder')
@section('subtitle','Buat undangan personal dan pantau pengisiannya.')
@section('content')
@if(!config('survey.email_enabled') || config('mail.default')!=='smtp')<div class="notice">Email belum diaktifkan. Anda tetap dapat menyalin tautan. Administrator server perlu mengatur SMTP, queue worker, dan scheduler sebelum mengaktifkan pengiriman.</div>@endif
<details class="panel distribution-form"><summary>＋ Buat undangan survei</summary><form action="{{ route('invitations.store') }}" method="post">@csrf<label>Kuesioner aktif<select name="survey_id" required><option value="">Pilih kuesioner</option>@foreach($surveys as $s)<option value="{{ $s->id }}">{{ $s->title }}</option>@endforeach</select></label><fieldset><legend>Klien penerima (pilih satu atau lebih)</legend><div class="client-checks">@forelse($clients as $c)<label class="check-row"><input type="checkbox" name="client_ids[]" value="{{ $c->id }}">{{ $c->name }} <small>{{ $c->email }}</small></label>@empty<p>Belum ada klien aktif.</p>@endforelse</div></fieldset><button class="btn primary">Buat tautan unik</button><p class="footnote">Tindakan ini hanya membuat undangan. Email dikirim setelah Anda memilih Kirim email pada undangan terkait.</p></form></details>
<div class="list-toolbar"><div class="tabs"><a href="{{ route('invitations.index') }}" class="{{ !request('status')?'selected':'' }}">Semua</a><a href="{{ route('invitations.index',['status'=>'pending']) }}" class="{{ request('status')==='pending'?'selected':'' }}">Belum selesai</a><a href="{{ route('invitations.index',['status'=>'completed']) }}" class="{{ request('status')==='completed'?'selected':'' }}">Selesai</a></div></div>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Klien / kuesioner</th><th>Pengisian</th><th>Email terakhir</th><th>Reminder berikutnya</th><th>Tindakan</th></tr></thead><tbody>@forelse($invitations as $i)<tr><td><strong>{{ $i->client->name }}</strong><small>{{ $i->survey->title }}</small><small>{{ $i->recipient_email }} @if($i->is_demo)· Contoh @endif</small></td><td><span class="badge {{ $i->completed_at?'green':'amber' }}">{{ $i->completed_at?'Selesai':($i->started_at?'Draf tersimpan':'Belum mengisi') }}</span></td><td>@php($delivery=$i->deliveries->sortByDesc('id')->first()){{ $delivery?['pending'=>'Dalam antrean','sent'=>'Terkirim','failed'=>'Gagal','skipped'=>'Dibatalkan'][$delivery->status]:'Belum dikirim' }}@if($delivery?->last_error)<small>{{ $delivery->last_error }}</small>@endif</td><td>{{ !$i->completed_at && $i->reminder_count<config('survey.max_reminders') ? ($i->reminder_at?->format('d M Y H:i')??'Setelah email pertama') : '—' }}<small>{{ $i->reminder_count }} reminder terkirim</small></td><td><div class="row-actions"><button class="text-button" type="button" data-copy="{{ $i->surveyUrl() }}">Salin tautan</button><a class="text-button" target="_blank" rel="noopener" href="{{ $i->surveyUrl() }}">Buka ↗</a>@if(!$i->completed_at && !$i->is_demo)<form method="post" action="{{ route('invitations.send',$i) }}" data-confirm="Kirim email ke {{ $i->recipient_email }}?">@csrf<button class="text-button" @disabled(!config('survey.email_enabled') || config('mail.default')!=='smtp')>{{ $i->sent_at?'Kirim reminder':'Kirim email' }}</button></form>@endif</div></td></tr>@empty<tr><td class="empty" colspan="5">Belum ada undangan. Buat tautan unik untuk klien Anda.</td></tr>@endforelse</tbody></table></div></section>{{ $invitations->links() }}@endsection
